# Generated by Django 5.2.5 on 2025-08-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="content",
        ),
        migrations.AddField(
            model_name="item",
            name="correct_answers",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="item",
            name="external_id",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="rationale",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="item",
            name="stem",
            field=models.TextField(blank=True, default=""),
        ),
    ]
