# Generated by Django 5.2.5 on 2025-08-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_remove_item_content_item_correct_answers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="keys",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
