# Generated by Django 5.2.5 on 2025-08-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_item_keys"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="content",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
