# Generated by Django 5.2.5 on 2025-08-24 20:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_item_content"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="keys",
            new_name="answer_options",
        ),
    ]
