// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efqpwkciytxgutfjppap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmcXB3a2NpeXR4Z3V0ZmpwcGFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4OTU5NTgsImV4cCI6MjA3MTQ3MTk1OH0.jK9XMKSoIXBRa92_RmQLAzNsowFYnFRkNr58AQwRn7M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});